export const GoogleTrendCategoryIds = {
    autosAndVehicles: "1",
    beautyAndFashion: "2",
    businessAndFinance: "3",
    climate: "20",
    entertainment: "4",
    foodAndDrink: "5",
    games: "6",
    health: "7",
    hobbiesAndLeisure: "8",
    jobsAndEducation: "9",
    lawAndGovernment: "10",
    other: "11",
    petsAndAnimals: "13",
    politics: "14",
    science: "15",
    shopping: "16",
    sports: "17",
    technology: "18",
    travelAndTransportation: "19",
} as const;
